use crate::asset_server::TRANSPARENT_CHAR;

pub fn char_to_5x5(char: char) -> Option<[[bool; 5]; 5]> {
    if char == ' ' || char == TRANSPARENT_CHAR {
        return None;
    }

    Some(match char.to_ascii_uppercase() {
        'A' => [
            [false, false, true, true, false],
            [false, true, false, false, true],
            [false, true, true, true, true],
            [false, true, false, false, true],
            [false, true, false, false, true],
        ],
        'B' => [
            [false, true, true, true, false],
            [false, true, false, false, true],
            [false, true, false, true, false],
            [false, true, false, false, true],
            [false, true, true, true, false],
        ],
        'C' => [
            [false, false, true, true, false],
            [false, true, false, false, false],
            [false, true, false, false, false],
            [false, true, false, false, false],
            [false, false, true, true, false],
        ],
        'D' => [
            [false, true, true, true, false],
            [false, true, false, false, true],
            [false, true, false, false, true],
            [false, true, false, false, true],
            [false, true, true, true, false],
        ],
        'E' => [
            [false, true, true, true, false],
            [false, true, false, false, false],
            [false, true, true, true, false],
            [false, true, false, false, false],
            [false, true, true, true, false],
        ],
        'F' => [
            [false, true, true, true, false],
            [false, true, false, false, false],
            [false, true, true, true, false],
            [false, true, false, false, false],
            [false, true, false, false, false],
        ],
        'G' => [
            [false, false, true, true, false],
            [false, true, false, false, true],
            [false, true, false, false, false],
            [false, true, false, true, true],
            [false, false, true, true, false],
        ],
        'H' => [
            [false, true, false, false, true],
            [false, true, false, false, true],
            [false, true, true, true, true],
            [false, true, false, false, true],
            [false, true, false, false, true],
        ],
        'I' => [
            [false, false, true, false, false],
            [false, false, true, false, false],
            [false, false, true, false, false],
            [false, false, true, false, false],
            [false, false, true, false, false],
        ],
        'J' => [
            [false, false, false, false, true],
            [false, false, false, false, true],
            [false, false, false, false, true],
            [false, false, true, false, true],
            [false, false, false, true, false],
        ],
        'K' => [
            [false, true, false, false, true],
            [false, true, false, true, false],
            [false, true, true, false, false],
            [false, true, false, true, false],
            [false, true, false, false, true],
        ],
        'L' => [
            [false, true, false, false, false],
            [false, true, false, false, false],
            [false, true, false, false, false],
            [false, true, false, false, false],
            [false, true, true, true, true],
        ],
        'M' => [
            [false, true, false, false, true],
            [false, true, true, true, true],
            [false, true, true, false, true],
            [false, true, false, false, true],
            [false, true, false, false, true],
        ],
        'N' => [
            [false, true, false, false, true],
            [false, true, true, false, true],
            [false, true, true, true, true],
            [false, true, false, true, true],
            [false, true, false, false, true],
        ],
        'O' => [
            [false, true, true, true, true],
            [false, true, false, false, true],
            [false, true, false, false, true],
            [false, true, false, false, true],
            [false, true, true, true, true],
        ],
        'P' => [
            [false, true, true, false, false],
            [false, true, false, true, false],
            [false, true, true, false, false],
            [false, true, false, false, false],
            [false, true, false, false, false],
        ],
        'Q' => [
            [false, true, true, true, true],
            [false, true, false, false, true],
            [false, true, false, false, true],
            [false, true, false, true, true],
            [false, true, true, false, true],
        ],
        'R' => [
            [false, true, true, false, false],
            [false, true, false, true, false],
            [false, true, true, false, false],
            [false, true, false, true, false],
            [false, true, false, false, true],
        ],
        'S' => [
            [false, false, true, true, false],
            [false, true, false, false, false],
            [false, false, true, true, false],
            [false, false, false, false, true],
            [false, false, true, true, false],
        ],
        'T' => [
            [false, true, true, true, false],
            [false, false, true, false, false],
            [false, false, true, false, false],
            [false, false, true, false, false],
            [false, false, true, false, false],
        ],
        'U' => [
            [false, true, false, false, true],
            [false, true, false, false, true],
            [false, true, false, false, true],
            [false, true, false, false, true],
            [false, true, true, true, true],
        ],
        'V' => [
            [false, true, false, false, true],
            [false, true, false, false, true],
            [false, true, false, true, false],
            [false, false, true, true, false],
            [false, false, true, false, false],
        ],
        'W' => [
            [false, true, false, false, true],
            [false, true, false, false, true],
            [false, true, false, true, true],
            [false, true, true, true, true],
            [false, true, false, false, true],
        ],
        'X' => [
            [false, true, false, false, true],
            [false, false, true, true, false],
            [false, false, false, true, false],
            [false, false, true, true, false],
            [false, true, false, false, true],
        ],
        'Y' => [
            [false, true, false, true, false],
            [false, true, false, true, false],
            [false, false, true, false, false],
            [false, false, true, false, false],
            [false, false, true, false, false],
        ],
        'Z' => [
            [false, true, true, true, true],
            [false, false, false, false, true],
            [false, false, true, true, false],
            [false, true, false, false, false],
            [false, true, true, true, true],
        ],

        _ => [[true; 5]; 5],
    })
}
